"""New-module scaffolding: generates a starter manifest YAML plus a matching
Python class stub for a brand-new automation/workflow/agent, so a user can
start building one from the dashboard without hand-writing the boilerplate
described in the README's "Adding a new module" section.
"""
import re
from pathlib import Path

import yaml

TIER_PACKAGE = {"automation": "automations", "workflow": "workflows", "agent": "agents"}
TIER_ENUM = {"automation": "AUTOMATION", "workflow": "WORKFLOW", "agent": "AGENT"}

# The description is embedded via repr() (never string-formatted directly into
# source), so any quotes/backslashes/newlines a user types stay a single,
# always-valid Python string literal -- no risk of generating broken source
# from an unlucky description.
PY_STUB_TEMPLATE = """\"\"\"Tier stub generated by the module scaffolding wizard -- fill in run() below.\"\"\"
from engine.base import BaseModule, Tier
from engine.context import ExecutionContext


class {class_name}(BaseModule):
    name = "{module_name}"
    tier = Tier.{tier_enum}
    description = {description!r}

    def run(self, context: ExecutionContext) -> dict:
        return {{}}
"""


class ScaffoldError(ValueError):
    pass


def _module_name_from(name: str) -> str:
    """A valid, importable Python module name derived from a free-text name
    -- same lowercase/underscore convention `webapp.pipelines._slugify` uses
    for pipeline slugs, plus the extra constraint that a module name must
    start with a letter (Python can't `import 123_thing`)."""
    slug = re.sub(r"[^a-z0-9]+", "_", name.strip().lower()).strip("_")
    if not slug:
        raise ScaffoldError("Module name must contain at least one letter or number.")
    if not slug[0].isalpha():
        raise ScaffoldError("Module name must start with a letter.")
    return slug


def _class_name_from(module_name: str) -> str:
    return "".join(part.capitalize() for part in module_name.split("_"))


def scaffold_module(tier: str, name: str, description: str, tier_dirs: dict) -> dict:
    """Write a starter <module_name>.py + <module_name>.yaml pair into the
    right tier directory. Raises ScaffoldError if the tier is unknown, the
    derived module name is invalid, or a module of that name already exists
    in this tier (either as a manifest or as a leftover file on disk)."""
    if tier not in TIER_PACKAGE:
        raise ScaffoldError(f"Unknown tier '{tier}'. Must be one of: automation, workflow, agent.")

    module_name = _module_name_from(name)
    class_name = _class_name_from(module_name)
    description = description.strip() or f"Describe what {module_name} does."

    directory = Path(tier_dirs[tier])
    yaml_path = directory / f"{module_name}.yaml"
    py_path = directory / f"{module_name}.py"
    if yaml_path.exists() or py_path.exists():
        raise ScaffoldError(f"A module named '{module_name}' already exists in this tier.")

    directory.mkdir(exist_ok=True)
    py_path.write_text(
        PY_STUB_TEMPLATE.format(
            description=description, class_name=class_name, module_name=module_name, tier_enum=TIER_ENUM[tier]
        )
    )

    manifest = {
        "name": module_name,
        "tier": tier,
        "entrypoint": f"{TIER_PACKAGE[tier]}.{module_name}:{class_name}",
        "description": description,
        "enabled": True,
        "inputs": [],
        "outputs": [],
    }
    yaml_path.write_text(yaml.safe_dump(manifest, sort_keys=False))

    return {
        "tier": tier,
        "name": module_name,
        "class_name": class_name,
        "yaml_path": str(yaml_path),
        "py_path": str(py_path),
    }
